// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"ero/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewProviderCatalog creates a new instance of MockReviewProviderCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewProviderCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewProviderCatalog {
	mock := &MockReviewProviderCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewProviderCatalog is an autogenerated mock type for the ReviewProviderCatalog type
type MockReviewProviderCatalog struct {
	mock.Mock
}

type MockReviewProviderCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewProviderCatalog) EXPECT() *MockReviewProviderCatalog_Expecter {
	return &MockReviewProviderCatalog_Expecter{mock: &_m.Mock}
}

// ListReviewProviderDescriptors provides a mock function for the type MockReviewProviderCatalog
func (_mock *MockReviewProviderCatalog) ListReviewProviderDescriptors(ctx context.Context) ([]ports.ReviewProviderDescriptor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListReviewProviderDescriptors")
	}

	var r0 []ports.ReviewProviderDescriptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.ReviewProviderDescriptor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.ReviewProviderDescriptor); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.ReviewProviderDescriptor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderCatalog_ListReviewProviderDescriptors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReviewProviderDescriptors'
type MockReviewProviderCatalog_ListReviewProviderDescriptors_Call struct {
	*mock.Call
}

// ListReviewProviderDescriptors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReviewProviderCatalog_Expecter) ListReviewProviderDescriptors(ctx interface{}) *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call {
	return &MockReviewProviderCatalog_ListReviewProviderDescriptors_Call{Call: _e.mock.On("ListReviewProviderDescriptors", ctx)}
}

func (_c *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call) Run(run func(ctx context.Context)) *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call) Return(reviewProviderDescriptors []ports.ReviewProviderDescriptor, err error) *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call {
	_c.Call.Return(reviewProviderDescriptors, err)
	return _c
}

func (_c *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call) RunAndReturn(run func(ctx context.Context) ([]ports.ReviewProviderDescriptor, error)) *MockReviewProviderCatalog_ListReviewProviderDescriptors_Call {
	_c.Call.Return(run)
	return _c
}
