// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"ero/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewProviderClientFactory creates a new instance of MockReviewProviderClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewProviderClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewProviderClientFactory {
	mock := &MockReviewProviderClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewProviderClientFactory is an autogenerated mock type for the ReviewProviderClientFactory type
type MockReviewProviderClientFactory struct {
	mock.Mock
}

type MockReviewProviderClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewProviderClientFactory) EXPECT() *MockReviewProviderClientFactory_Expecter {
	return &MockReviewProviderClientFactory_Expecter{mock: &_m.Mock}
}

// CreateReviewProviderClient provides a mock function for the type MockReviewProviderClientFactory
func (_mock *MockReviewProviderClientFactory) CreateReviewProviderClient(ctx context.Context, descriptor ports.ReviewProviderDescriptor) (ports.ReviewProviderClient, error) {
	ret := _mock.Called(ctx, descriptor)

	if len(ret) == 0 {
		panic("no return value specified for CreateReviewProviderClient")
	}

	var r0 ports.ReviewProviderClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ReviewProviderDescriptor) (ports.ReviewProviderClient, error)); ok {
		return returnFunc(ctx, descriptor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ReviewProviderDescriptor) ports.ReviewProviderClient); ok {
		r0 = returnFunc(ctx, descriptor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.ReviewProviderClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.ReviewProviderDescriptor) error); ok {
		r1 = returnFunc(ctx, descriptor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderClientFactory_CreateReviewProviderClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReviewProviderClient'
type MockReviewProviderClientFactory_CreateReviewProviderClient_Call struct {
	*mock.Call
}

// CreateReviewProviderClient is a helper method to define mock.On call
//   - ctx context.Context
//   - descriptor ports.ReviewProviderDescriptor
func (_e *MockReviewProviderClientFactory_Expecter) CreateReviewProviderClient(ctx interface{}, descriptor interface{}) *MockReviewProviderClientFactory_CreateReviewProviderClient_Call {
	return &MockReviewProviderClientFactory_CreateReviewProviderClient_Call{Call: _e.mock.On("CreateReviewProviderClient", ctx, descriptor)}
}

func (_c *MockReviewProviderClientFactory_CreateReviewProviderClient_Call) Run(run func(ctx context.Context, descriptor ports.ReviewProviderDescriptor)) *MockReviewProviderClientFactory_CreateReviewProviderClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.ReviewProviderDescriptor
		if args[1] != nil {
			arg1 = args[1].(ports.ReviewProviderDescriptor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewProviderClientFactory_CreateReviewProviderClient_Call) Return(reviewProviderClient ports.ReviewProviderClient, err error) *MockReviewProviderClientFactory_CreateReviewProviderClient_Call {
	_c.Call.Return(reviewProviderClient, err)
	return _c
}

func (_c *MockReviewProviderClientFactory_CreateReviewProviderClient_Call) RunAndReturn(run func(ctx context.Context, descriptor ports.ReviewProviderDescriptor) (ports.ReviewProviderClient, error)) *MockReviewProviderClientFactory_CreateReviewProviderClient_Call {
	_c.Call.Return(run)
	return _c
}
